--- 
server: 
  port: 8090
spring: 
  datasource:
    tomcat:
      max-wait: 20000
      max-active: 50
      max-idle: 20
      min-idle: 15
      test-while-idle: true
      validation-query: SELECT 1
    dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
    driver-class-name: com.mysql.jdbc.Driver
    password: Fsoft12345
    url: "jdbc:mysql://cloudmonitoring.caec6rjyfhfm.us-east-1.rds.amazonaws.com:3306/CloudMonitoring?useUnicode=true&characterEncoding=utf8"
    username: root
  jpa: 
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: false
    hibernate: 
      ddl-auto: update
      naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
    properties:
      hibernate.cache.use_query_cache: false
      hibernate.cache.use_second_level_cache: false
      hibernate.generate_statistics: true
      org.hibernate.envers.audit_table_suffix: _history
      dialect: org.hibernate.dialect.MySQLDialect
    show_sql: true